name: Module-ScanDeps
module_name: Module::ScanDeps
version: 0.31
abstract: Recursively scan Perl programs for dependencies
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
no_index:
  directory:
    - inc
private:
  directory:
    - inc
generated_by: Module::Install version 0.25
