--- 
abstract: Recursively scan Perl code for dependencies
author: Audrey Tang <autrijus@autrijus.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Module-ScanDeps
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::Spec: 0
  File::Temp: 0
  Module::Build::ModuleInfo: 0
  perl: 5.004
version: 0.76
