---
abstract: 'Recursively scan Perl code for dependencies'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-ScanDeps
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0
  File::Temp: 0
  Module::Build::ModuleInfo: 0
  perl: 5.6.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.86
