abstract: Recursively scan Perl code for dependencies
author: 'Audrey Tang <autrijus@autrijus.org>'
distribution_type: module
generated_by: Module::Install version 0.51
license: perl
name: Module-ScanDeps
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.004
version: 0.53
